nama=("IRA RASILA WATIN")
jk=("Perempuan")
agama=("Islam")
ttl=("sumbek 22 Juli 2005")
Alamat=("sumbek desa muncan kecamatan kopang")
hobi=("membaca")
Prodi=("Teknik Informatika")
Nim=("TI20230013")
smt=int(2)
Angkt=int(2023)
sts=("Aktif")
wa=int(+6283129188042)
Ig=("irarasilawatin")
email=("rasila477@gmail.com")
sd=("SD Negeri penaka")
smp=("SMPN islam al-gafuriah")
sma= ("SMK darul kamilin")
pg=("STMIK Lombok")


print("|  BIODATA PRIBADI  |")
print("_________________________") 
print("")
print("Nama                             =",nama)
print("Jenis Kelamin                    =",jk) 
print("Agama                            =",agama) 
print("Tempat, tanggal lahir            =",ttl) 
print("Alamat                           =",Alamat) 
print("Hobi                             =", hobi)
print("")


print("|  SOSIAL MEDIA   |") 
print("")
print("WhatsApp                         =",wa)
print("Instagram                        =",Ig)
print("Email                            =",email) 
print("")


print("|   PERGURUAN TINGGI     |")
print("")
print("Kampus                           =",pg)
print("Prodi/Jurusan                    =",Prodi)
print("NIM                              =",Nim)
print("Semester                         =",smt)
print("Angkatan                         =",Angkt)
print("Status Mahasiswa                 =",sts)
print("")


print("|      PENDIDIKAN       |")
print("")
print("SD                               =",sd)
print("SMP                              =",smp)
print("SMK                              =",smk)
print("")
print("_____________________________________")


